spring:
    profiles:
        include: security
    datasource:
        url: ${MYSQL_URL}
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: ${MYSQL_USERNAME}
        password: ${MYSQL_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: create
        defer-datasource-initialization: true
    sql:
        init:
            mode: always
